### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by theodorusclarence** [theodorusclarence/apsi-academy#1]
- [x] Review per detail
- [x] Akses Kelas
- [x] Login
- [x] Register
- [ ] Checkout -> nambahin ke invoice
- [x] Profil
- [x] Cart
- [x] Detail Kelas
- [ ] Cek ulang token midtrans snap
- [x] Filter di cari kelas
